#!/usr/bin/env python3

import json
import os
from pathlib import Path
import shutil

import dbus
import dbus.service
from dbus.mainloop.glib import DBusGMainLoop
from gi.repository import GLib


SERVICE_NAME = "net.lliurex.KScreenSystem"
OBJECT_PATH = "/net/lliurex/KScreenSystem"
INTERFACE = "net.lliurex.KScreenSystem"

POLKIT_ACTIONS = {
        "updateGlobalConfig":"net.lliurex.kscreen.updateglobalconfig",
        "setGlobalConfig":"net.lliurex.kscreen.setglobalconfig",
        "removeGlobalConfig":"net.lliurex.kscreen.removeconfig"
        }

ETC_CONFIG_FILE = Path("/etc/skel/.config/kwinoutputconfig.json")
VAR_CONFIG_FILE = Path("/var/lib/kscreensystem/kwinoutputconfig.json")

ALL_USERS_CONFIG_PATH = Path("/usr/share/kscreensystem/kscreensystemallusers.sh")
PROFILE_D_PATH = Path("/etc/profile.d/kscreensystemallusers.sh")


class KScreenSystemService(dbus.service.Object):

    def __init__(self, bus, object_path):
        self.bus = bus
        super().__init__(bus, object_path)

    def check_authorization(self,polkit_action, sender):

        authority_obj = self.bus.get_object(
            "org.freedesktop.PolicyKit1",
            "/org/freedesktop/PolicyKit1/Authority"
        )

        authority = dbus.Interface(
            authority_obj,
            "org.freedesktop.PolicyKit1.Authority"
        )

        subject = (
            "system-bus-name",
            {
                "name": dbus.String(sender)
            }
        )

        result = authority.CheckAuthorization(
            subject,
            polkit_action,
            {},
            dbus.UInt32(1),  # AllowUserInteraction
            ""
        )

        return bool(result[0])

    '''

        DBUS Method: ExistsGlobalConfig

    '''
    @dbus.service.method(
        INTERFACE,
        in_signature="",
        out_signature="b"
    )
    def ExistsGlobalConfig(self):
        return VAR_CONFIG_FILE.exists()
        

    '''

        DBUS Method: StatusGlobalConfig

    '''
    @dbus.service.method(
        INTERFACE,
        in_signature="",
        out_signature="i"
    )
    def StatusGlobalConfig(self):
        if ETC_CONFIG_FILE.exists():
            if PROFILE_D_PATH.exists():
                return 2
            else:
                return 1
        else:
            return 0


    '''

        DBUS Method: UpdateGlobalConfig
        
    '''
    @dbus.service.method(
        INTERFACE,
        in_signature="s",
        out_signature="b",
        sender_keyword="sender"
    )
    def UpdateGlobalConfig(self, path, sender=None):

        if not self.check_authorization( POLKIT_ACTIONS["updateGlobalConfig"], sender ):
            raise dbus.exceptions.DBusException(
                "org.freedesktop.DBus.Error.AccessDenied",
                "Authentication failed"
            )

        VAR_CONFIG_FILE.parent.mkdir(parents=True, exist_ok=True)
        ORIGIN_PATH = Path(path)
        if ORIGIN_PATH.exists():
            shutil.copy(ORIGIN_PATH, VAR_CONFIG_FILE)
        return True



    '''

        DBUS Method: SetGlobalConfig

    '''
    @dbus.service.method(
        INTERFACE,
        in_signature="b",
        out_signature="b",
        sender_keyword="sender"
    )
    def SetGlobalConfig(self, allUsers ,sender=None):

        if not self.check_authorization( POLKIT_ACTIONS["setGlobalConfig"], sender ):
            raise dbus.exceptions.DBusException(
                "org.freedesktop.DBus.Error.AccessDenied",
                "Authentication failed"
            )

        if VAR_CONFIG_FILE.exists():
            if not ETC_CONFIG_FILE.exists():
                ETC_CONFIG_FILE.hardlink_to(VAR_CONFIG_FILE)
            if allUsers:
                if not PROFILE_D_PATH.exists():
                    shutil.copy(ALL_USERS_CONFIG_PATH, PROFILE_D_PATH)
            else:
                if PROFILE_D_PATH.exists():
                    PROFILE_D_PATH.unlink()
        else:
            return False
        return True


    '''

        DBUS Method: RemoveGlobalConfig

    '''
    @dbus.service.method(
        INTERFACE,
        in_signature="",
        out_signature="b",
        sender_keyword="sender"
    )
    def RemoveGlobalConfig(self, sender=None):
        if not self.check_authorization( POLKIT_ACTIONS["removeGlobalConfig"], sender ):
            raise dbus.exceptions.DBusException(
                "org.freedesktop.DBus.Error.AccessDenied",
                "Authentication failed"
            )

        if ETC_CONFIG_FILE.exists():
            ETC_CONFIG_FILE.unlink()

        return True


def main():
    DBusGMainLoop(set_as_default=True)

    bus = dbus.SystemBus()

    name = dbus.service.BusName(
        SERVICE_NAME,
        bus
    )

    KScreenSystemService(bus, OBJECT_PATH)

    print("net.lliurex.KScreenSystem service running")

    GLib.MainLoop().run()


if __name__ == "__main__":
    main()
